#!/bin/sh 
# Copyright 2003 Regents of the University of California

# SETI_BOINC is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later
# version.

# SETI_BOINC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with SETI_BOINC; see the file COPYING.  If not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

filename=/tmp/`echo $1 | /bin/sed 's/\.sql//'`
echo begin_refs > $filename
mawk -f /mnt/usb/boinc-rpi/project_seti/db/find_references.awk $1 | /bin/sed 's/[(),;]//g' | /usr/bin/sort | /usr/bin/uniq >> $filename
echo end_refs >> $filename
/bin/cat $1 | /usr/bin/tr "[A-Z]" "[a-z]" | /bin/sed 's/\`//g' >>$filename

mawk -f /mnt/usb/boinc-rpi/project_seti/db/schema_to_class.awk $filename
INDENT=
if test -n "$INDENT" 
then
   --c --indent-classes --indent-switches --brackets=attach --convert-tabs $filename.h
   --c --indent-classes --indent-switches --brackets=attach --convert-tabs $filename.cpp
fi
  
/bin/mv $filename.cpp .
/bin/mv $filename.h .
/bin/rm $filename*
